name: Upload artifacts as release asset

on:
  release:
    types: [ created ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install beeware
      - name: Create with beeware
        run: |
          briefcase create
      - name: Package with beeware
        run: |
          briefcase build
          briefcase package
      - uses: actions/upload-artifact@v2
        with:
          name: vakhangya-app
          path: windows\Vakhangya-0.1.0.msi
